// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instruments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInstruments = `-- name: CountInstruments :one
SELECT COUNT(*) FROM instruments
`

func (q *Queries) CountInstruments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInstruments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertInstrument = `-- name: InsertInstrument :one
INSERT INTO instruments (
    instrument_token, exchange_token, tradingsymbol,
    name, last_price, expiry, strike, tick_size, 
    lot_size, instrument_type, segment, exchange) VALUES 
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) 
    RETURNING id, instrument_token, exchange_token, tradingsymbol, name, last_price, expiry, strike, tick_size, lot_size, instrument_type, segment, exchange
`

type InsertInstrumentParams struct {
	InstrumentToken int64            `json:"instrument_token"`
	ExchangeToken   int64            `json:"exchange_token"`
	Tradingsymbol   string           `json:"tradingsymbol"`
	Name            string           `json:"name"`
	LastPrice       float64          `json:"last_price"`
	Expiry          pgtype.Timestamp `json:"expiry"`
	Strike          float64          `json:"strike"`
	TickSize        float64          `json:"tick_size"`
	LotSize         float64          `json:"lot_size"`
	InstrumentType  string           `json:"instrument_type"`
	Segment         string           `json:"segment"`
	Exchange        string           `json:"exchange"`
}

func (q *Queries) InsertInstrument(ctx context.Context, arg InsertInstrumentParams) (*Instrument, error) {
	row := q.db.QueryRow(ctx, insertInstrument,
		arg.InstrumentToken,
		arg.ExchangeToken,
		arg.Tradingsymbol,
		arg.Name,
		arg.LastPrice,
		arg.Expiry,
		arg.Strike,
		arg.TickSize,
		arg.LotSize,
		arg.InstrumentType,
		arg.Segment,
		arg.Exchange,
	)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.InstrumentToken,
		&i.ExchangeToken,
		&i.Tradingsymbol,
		&i.Name,
		&i.LastPrice,
		&i.Expiry,
		&i.Strike,
		&i.TickSize,
		&i.LotSize,
		&i.InstrumentType,
		&i.Segment,
		&i.Exchange,
	)
	return &i, err
}

const truncateInstrument = `-- name: TruncateInstrument :one
TRUNCATE TABLE instruments
`

type TruncateInstrumentRow struct {
}

func (q *Queries) TruncateInstrument(ctx context.Context) (*TruncateInstrumentRow, error) {
	row := q.db.QueryRow(ctx, truncateInstrument)
	var i TruncateInstrumentRow
	err := row.Scan()
	return &i, err
}
