// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Instrument struct {
	ID              int32            `json:"id"`
	InstrumentToken int64            `json:"instrument_token"`
	ExchangeToken   int64            `json:"exchange_token"`
	Tradingsymbol   string           `json:"tradingsymbol"`
	Name            string           `json:"name"`
	LastPrice       float64          `json:"last_price"`
	Expiry          pgtype.Timestamp `json:"expiry"`
	Strike          float64          `json:"strike"`
	TickSize        float64          `json:"tick_size"`
	LotSize         float64          `json:"lot_size"`
	InstrumentType  string           `json:"instrument_type"`
	Segment         string           `json:"segment"`
	Exchange        string           `json:"exchange"`
}
