// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CountInstruments(ctx context.Context) (int64, error)
	InsertInstrument(ctx context.Context, arg InsertInstrumentParams) (*Instrument, error)
	TruncateInstrument(ctx context.Context) (*TruncateInstrumentRow, error)
}

var _ Querier = (*Queries)(nil)
